'use strict';
let scenario = null;
let reportMode = 'METAR';

const AIRPORTS = [
  {icao:'SBMI',name:'Maricá',elev:4},{icao:'SBJF',name:'Juiz de Fora',elev:910},{icao:'SBRJ',name:'Santos Dumont',elev:3},{icao:'SBGL',name:'Galeão',elev:9},{icao:'SBGR',name:'Guarulhos',elev:750},{icao:'SBCF',name:'Confins',elev:828},{icao:'SBBR',name:'Brasília',elev:1066},{icao:'SBPA',name:'Porto Alegre',elev:3},{icao:'SBSV',name:'Salvador',elev:20},{icao:'SBKP',name:'Viracopos',elev:661}
];
const WEATHER = [null,'-RA','RA','+RA','DZ','-DZ','SHRA','TSRA','BR','FG','HZ','FU','SA','DU','PO','SQ','VCFG','VCTS','RERA','RETS'];
const WEATHER_LABELS = {'-RA':'Chuva fraca','RA':'Chuva moderada','+RA':'Chuva forte','DZ':'Chuvisco','-DZ':'Chuvisco fraco','SHRA':'Pancadas de chuva','TSRA':'Trovoada com chuva','BR':'Névoa úmida','FG':'Nevoeiro','HZ':'Névoa seca','FU':'Fumaça','SA':'Areia','DU':'Poeira extensa','PO':'Poeira/areia em redemoinhos','SQ':'Rajada forte / squall','VCFG':'Nevoeiro na vizinhança','VCTS':'Trovoada na vizinhança','RERA':'Chuva recente','RETS':'Trovoada recente'};
const CLOUD_TYPES = ['CI','CC','CS','AC','AS','NS','SC','ST','CU','TCU','CB'];
const CLOUD_TYPE_LABELS = {CI:'Cirrus',CC:'Cirrocumulus',CS:'Cirrostratus',AC:'Altocumulus',AS:'Altostratus',NS:'Nimbostratus',SC:'Stratocumulus',ST:'Stratus',CU:'Cumulus',TCU:'Cumulus congestus',CB:'Cumulonimbus'};
const CLOUD_BANDS_M = {ST:[90,900],SC:[180,1800],CU:[300,2200],TCU:[500,2600],CB:[500,3000],NS:[600,3000],AC:[1800,5000],AS:[1800,5500],CS:[3500,7500],CI:[4500,9000],CC:[4500,9000]};
const OKTA_TO_AMOUNT = {1:'FEW',2:'FEW',3:'SCT',4:'SCT',5:'BKN',6:'BKN',7:'BKN',8:'OVC'};
const MAX_CLOUD_BASE_M = 3000, MAX_CLOUD_BASE_FT = 9999;
const $ = id => document.getElementById(id);
const randInt = (a,b) => Math.floor(Math.random()*(b-a+1))+a;
const choice = a => a[Math.floor(Math.random()*a.length)];
const pad = (n,w=2) => String(n).padStart(w,'0');
const fmt = (v,d=0) => Number(v).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});
const metersToFeet = m => Math.round(m*3.280839895);
const metarCloudHeightFt = m => Math.floor(metersToFeet(m)/100)*100;
const cToMetar = v => { v=Math.trunc(v); return v<0 ? `M${String(Math.abs(v)).padStart(2,'0')}` : String(v).padStart(2,'0'); };
const qfeFromQnh = (qnh,elevFt) => qnh*Math.pow(1-(0.0000225577*elevFt),5.2559);
const amountFromOktas = o => OKTA_TO_AMOUNT[o];
function cloudGroup(c){const h=metarCloudHeightFt(c.altitude_m)/100; const suffix=(c.type==='CB'||c.type==='TCU')?c.type:''; return `${amountFromOktas(c.oktas)}${String(h).padStart(3,'0')}${suffix}`;}
function randomCloudLayer(used,minHeight){
  const available=CLOUD_TYPES.filter(c=>!used.has(c)); const type=choice(available); let [low,high]=CLOUD_BANDS_M[type]; low=Math.max(low,minHeight+choice([30,60,90])); if(low>=high) low=Math.max(30,high-100);
  const base=Math.max(30,Math.floor((low+randInt(0,Math.max(0,Math.floor((high-low)/30)))*30)/30)*30); const oktas=randInt(1,8);
  return {type,type_label:CLOUD_TYPE_LABELS[type],oktas,coverage_raw:`${oktas}/8`,altitude_m:base,altitude_ft_exact:metersToFeet(base),altitude_ft_metar:metarCloudHeightFt(base),amount:amountFromOktas(oktas),group:cloudGroup({type,oktas,altitude_m:base})};
}
function makeCloudObservation(){const count=choice([1,2,2,3,3]); const layers=[],used=new Set(); let prev=0; for(let i=0;i<count;i++){const c=randomCloudLayer(used,prev); layers.push(c);used.add(c.type);prev=c.altitude_m;} return layers.sort((a,b)=>a.altitude_m-b.altitude_m);}
function cloudWithinLimit(c){return c.altitude_m<=MAX_CLOUD_BASE_M && c.altitude_ft_exact<=MAX_CLOUD_BASE_FT;}
function reportableCloudGroups(layers){const eligible=[...layers].sort((a,b)=>a.altitude_m-b.altitude_m).filter(cloudWithinLimit); const selected=[]; if(eligible.length) selected.push(eligible[0]); for(const c of eligible.slice(1)){if(c.oktas>=3){selected.push(c);break;}} const last=selected.length?selected[selected.length-1].altitude_m:-1; for(const c of eligible){if(c.altitude_m>last&&c.oktas>=5){selected.push(c);break;}} for(const c of eligible){if((c.type==='CB'||c.type==='TCU')&&!selected.includes(c)) selected.push(c);} return [...new Set(selected)].sort((a,b)=>a.altitude_m-b.altitude_m);}
function makeScenario(){
  const apt=choice(AIRPORTS), day=randInt(1,28), hour=randInt(0,23); const calm=Math.random()<.07; let wind_dir=0,wind_speed=0,gust=0;
  if(!calm){wind_dir=randInt(1,35)*10;wind_speed=randInt(3,28);if(Math.random()<.22)gust=wind_speed+randInt(10,18);}
  const visibility=choice([300,500,800,1000,1500,2000,3000,4000,5000,6000,8000,9999,10000]), weather=choice(WEATHER), sky_obscured=Math.random()<.08;
  const clouds=sky_obscured?[]:makeCloudObservation(), vv=sky_obscured?choice([90,120,180,240,300,450,600]):null;
  const temp=randInt(5,34), dew=Math.max(-5,temp-randInt(1,8)), qnh=Math.round((990+Math.random()*40)*10)/10, qne=1013.25, qfe=Math.round(qfeFromQnh(qnh,apt.elev)*10)/10;
  let variable=null; if(!calm&&Math.random()<.15&&wind_speed>=6){const spread=choice([40,60,80,100]),lo=(wind_dir-spread/2+360)%360,hi=(wind_dir+spread/2)%360; variable=[lo,hi];}
  const reportable_clouds=reportableCloudGroups(clouds), out_of_range_clouds=clouds.filter(c=>!cloudWithinLimit(c)); let cavok=visibility>=10000&&!weather&&!reportable_clouds.length&&!sky_obscured;
  return {report_type:'METAR',airport:apt,station:apt.icao,day,hour,minute:0,wind_dir,wind_speed,gust,variable,visibility:cavok?10000:visibility,weather,weather_label:WEATHER_LABELS[weather]||'Sem tempo significativo',clouds,reportable_clouds,out_of_range_clouds,cloud_limit_m:MAX_CLOUD_BASE_M,cloud_limit_ft:MAX_CLOUD_BASE_FT,vv,sky_obscured,temp,dew,qnh,qne,qfe,cavok};
}
function makeSpeciFromMetar(base){const s=structuredClone(base);s.report_type='SPECI';s.minute=choice([5,8,12,18,24,32,38,44,48,52]); const triggers=['visibilidade predominante piorou','mudança significativa na intensidade da precipitação','mudança significativa na velocidade do vento','rajada atingiu valor significativo','base de nuvem passou por limiar operacional']; s.trigger=choice(triggers);
  if(s.trigger===triggers[0]){const current=s.visibility<10000?s.visibility:9999;const lower=[1000,1500,2000,3000,4000,5000].filter(v=>v<current);s.visibility=choice(lower.length?lower:[3000]);s.cavok=false;}
  else if(s.trigger===triggers[1]){s.weather=choice(['RA','+RA','TSRA','SHRA']);s.weather_label=WEATHER_LABELS[s.weather];s.cavok=false;}
  else if(s.trigger===triggers[2]){s.wind_speed=Math.min(45,Math.max(10,s.wind_speed+choice([10,12,15])));if(s.wind_speed>=15)s.gust=Math.max(s.gust,s.wind_speed+8);}
  else if(s.trigger===triggers[3]){s.wind_speed=Math.max(15,s.wind_speed);s.gust=Math.min(55,Math.max(s.wind_speed+10,25));}
  else {if(s.clouds.length){const c=s.clouds.reduce((a,b)=>a.altitude_m<b.altitude_m?a:b);c.altitude_m=choice([90,120,150,180,300,450,600]);c.altitude_ft_exact=metersToFeet(c.altitude_m);c.altitude_ft_metar=metarCloudHeightFt(c.altitude_m);c.group=cloudGroup(c);s.reportable_clouds=reportableCloudGroups(s.clouds);}else{s.sky_obscured=true;s.vv=choice([30,60,150,300]);s.cavok=false;}}
  s.reportable_clouds=s.sky_obscured?[]:reportableCloudGroups(s.clouds);s.out_of_range_clouds=s.clouds.filter(c=>!cloudWithinLimit(c));return s;
}
function buildExpected(s){const p=[s.report_type,s.station,`${pad(s.day)}${pad(s.hour)}${pad(s.minute)}Z`]; if(s.wind_speed===0)p.push('00000KT'); else {let w=`${String(s.wind_dir).padStart(3,'0')}${String(s.wind_speed).padStart(2,'0')}`;if(s.gust)w+=`G${String(s.gust).padStart(2,'0')}`;p.push(w+'KT');if(s.variable)p.push(`${String(Math.round(s.variable[0])).padStart(3,'0')}V${String(Math.round(s.variable[1])).padStart(3,'0')}`);}
  if(s.cavok)p.push('CAVOK'); else {p.push(s.visibility>=10000?'9999':String(s.visibility).padStart(4,'0'));if(s.weather)p.push(s.weather);if(s.sky_obscured)p.push(`VV${String(Math.floor(s.vv/30)).padStart(3,'0')}`);else if(s.reportable_clouds.length)p.push(...s.reportable_clouds.map(cloudGroup));else p.push('NSC');}
  p.push(`${cToMetar(s.temp)}/${cToMetar(s.dew)}`,`Q${String(Math.round(s.qnh)).padStart(4,'0')}`,'=');return p.join(' ');}
function normalize(t){return (t||'').toUpperCase().replace(/=/g,' = ').trim().split(/\s+/).filter(Boolean);}
function compare(expected,answer){const e=normalize(expected),a=normalize(answer);const mismatches=[];for(let i=0;i<Math.max(e.length,a.length);i++){const av=a[i]||'—',ev=e[i]||'—';if(av!==ev)mismatches.push({position:i+1,entered:av,expected:ev});}return {correct:a.join(' ')===e.join(' '),score:Math.max(0,Math.round(100*(1-mismatches.length/Math.max(1,e.length)))),mismatches};}
function render(s){$('airport').textContent=`${s.station} — ${s.airport.name}`;$('datetime').textContent=`${pad(s.day)}${pad(s.hour)}${pad(s.minute)}Z`;$('reportMode').textContent=`${s.report_type} — ${s.minute===0?'hora cheia':'fora da hora cheia'}`;$('visibility').textContent=s.cavok?'10.000+':fmt(s.visibility);$('weather').textContent=s.weather?`${s.weather} — ${s.weather_label}`:'Sem fenômeno significativo';$('temp').textContent=s.temp;$('dew').textContent=s.dew;$('qnh').textContent=fmt(s.qnh,1);$('qfe').textContent=fmt(s.qfe,1);$('qne').textContent=fmt(s.qne,2);$('elevation').textContent=fmt(s.airport.elev);const wind=s.wind_speed===0?'000° / 00 kt':`${String(s.wind_dir).padStart(3,'0')}° / ${String(s.wind_speed).padStart(2,'0')} kt${s.gust?' G'+String(s.gust).padStart(2,'0'):''}`;$('windRead').textContent=wind;$('needle').style.transform=`rotate(${s.wind_dir}deg)`;$('variableRead').textContent=s.variable?`Variação direcional: ${String(Math.round(s.variable[0])).padStart(3,'0')}°–${String(Math.round(s.variable[1])).padStart(3,'0')}°`:(s.wind_speed===0?'Calmaria':'Direção predominante');renderClouds(s);}
function renderClouds(s){const rows=$('cloudRows'),special=$('cloudSpecial');rows.innerHTML='';special.innerHTML='';if(s.cavok){special.innerHTML='<span class="cloud-chip">CAVOK — não há nuvens significativas para codificar</span>';return;}if(s.sky_obscured){special.innerHTML=`<span class="cloud-chip warning">CÉU OBSCURECIDO — visibilidade vertical: ${fmt(s.vv)} m</span>`;return;}s.clouds.forEach((c,i)=>{const tr=document.createElement('tr');tr.innerHTML=`<td><span class="layer-badge">CAMADA ${i+1}</span></td><td><b>${c.type}</b><small>${c.type_label}</small></td><td class="oktas"><b>${c.oktas}/8</b></td><td><b>${fmt(c.altitude_m)} m</b></td><td class="hint-cell">converter para ft</td>`;rows.appendChild(tr);});if(s.clouds.length)special.innerHTML='<span class="cloud-chip neutral">Todas as camadas permanecem visíveis para treinamento. Na correção, somente bases ≤ 3.000 m e ≤ 9.999 ft podem ser reportadas.</span>';else special.innerHTML='<span class="cloud-chip">NSC — sem nuvens significativas</span>';}
function resetResult(){ $('answer').value='';$('result').className='result hidden'; }
function newScenario(){scenario=makeScenario();reportMode='METAR';render(scenario);resetResult();$('status').textContent='● METAR REGULAR — HORA CHEIA';$('speciInfo').className='training-note hidden';}
function generateSpeci(){if(!scenario)scenario=makeScenario();scenario=makeSpeciFromMetar(scenario);reportMode='SPECI';render(scenario);resetResult();$('status').textContent='● SPECI — ALTERAÇÃO SIGNIFICATIVA';$('speciInfo').className='training-note';$('speciInfo').innerHTML=`<b>SIMULAÇÃO SPECI:</b> mesmo aeródromo do METAR regular. Evento gerador: <b>${escapeHtml(scenario.trigger)}</b>. A observação ocorreu às <b>${pad(scenario.hour)}:${pad(scenario.minute)}Z</b>, fora da hora cheia. O aluno deve confeccionar somente o SPECI atual.`;}
function checkAnswer(){const d=compare(buildExpected(scenario),$('answer').value);const el=$('result');el.className='result '+(d.correct?'ok':'bad');let html=`<b>${d.correct?'✓ INFORME CORRETO':'✗ HÁ DIVERGÊNCIAS'}</b><br>Desempenho: <b>${d.score}%</b><br><br>`;if(!d.correct){html+=`<b>Gabarito didático:</b><br><span class="answer-key">${escapeHtml(buildExpected(scenario))}</span><br><br>`;if(d.mismatches.length)html+='<b>Pontos divergentes:</b><br>'+d.mismatches.map(m=>`Grupo ${m.position}: informado <b>${escapeHtml(m.entered)}</b> → esperado <b>${escapeHtml(m.expected)}</b>`).join('<br>');if(scenario.out_of_range_clouds.length)html+='<br><br><b>Camadas fora da faixa de correção:</b><br>'+scenario.out_of_range_clouds.map(c=>`${c.type} — ${fmt(c.altitude_m)} m (≈ ${fmt(c.altitude_ft_exact)} ft)`).join('<br>')+'<br><small>Elas aparecem no cenário, mas não são aceitas na correção deste exercício.</small>';}else{html+='Excelente. A sequência e os grupos coincidem com o cenário gerado.';if(scenario.out_of_range_clouds.length)html+='<br><br><small>Você também identificou corretamente as camadas acima da faixa de correção.</small>';}el.innerHTML=html;}
function showAnswer(){const el=$('result');el.className='result';el.innerHTML=`<b>GABARITO</b><br><span class="answer-key">${escapeHtml(buildExpected(scenario))}</span><br><br><small>O gabarito foi calculado localmente a partir do cenário. As camadas acima de 3.000 m / 9.999 ft permanecem visíveis, mas não entram na correção deste exercício.</small>`;}
function escapeHtml(t){return String(t).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
newScenario();
